# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/Reference/yml.html
runners:
  - name: "aws-runner-x86_64"
    # Cloud Provider: AWS
    cloud: "aws"
    # Cheapest VM on AWS
    instance_type: "c5a.2xlarge"
    region: "us-east-1"
    vpc: "vpc-0825bc37b6c12adbb"
    # Ubuntu 22.04 amd64
    machine_image: "ami-08c40ec9ead489470"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-aws-runner-x86_64"
  - name: "aws-runner-aarch64"
    # Cloud Provider: AWS
    cloud: "aws"
    # Cheapest VM on AWS
    instance_type: "c6g.16xlarge"
    region: "us-east-1"
    vpc: "vpc-0825bc37b6c12adbb"
    # Ubuntu 22.04 arm64
    machine_image: "ami-019c02e2c21237ee7"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-aws-runner-aarch64"