# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/Reference/yml.html
runners:
  - name: "aws-runner"
    # Cloud Provider: AWS
    cloud: "aws"
    # Cheapest VM on AWS
    instance_type: "t2.xlarge"
    region: "us-east-1"
    vpc: "vpc-0825bc37b6c12adbb"
    # Ubuntu-22.4, ami image
    machine_image: "ami-08c40ec9ead489470"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-aws-runner"