---
name: Release

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v2.1.10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      if: steps['release']['outputs']['published'] == 'true'
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      if: steps['release']['outputs']['published'] == 'true'
      uses: docker/setup-buildx-action@v1
    - name: Package via Docker Buildx
      if: steps['release']['outputs']['published'] == 'true'
      run: |
        docker buildx build --platform linux/arm64,linux/amd64 --output type=tar,dest=out.tar.gz .
        tar -xvf out.tar.gz
        tar -C linux_arm64/ -czvf linux-arm64.tar.gz .
        tar -C linux_amd64/ -czvf linux-amd64.tar.gz .
    - name: Add Release Artifacts to the Github Release
      if: steps['release']['outputs']['published'] == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.release.outputs.release-git-tag}}
        files: |
          linux-arm64.tar.gz
          linux-amd64.tar.gz
