---
name: Release

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      env:
        token: ${{ secrets.GITHUB_PAT }}
    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v2.1.10
      env:
        GH_TOKEN: ${{ secrets.GITHUB_PAT }}
        # requires a PAT so the tag triggers the packaging action
