---
name: Release

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Release
      id: release
      uses: ahmadnassri/action-semantic-release@v2.1.10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  artifacts:
    needs: release
    name: Create Release Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_type: [apk,deb]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Package via Docker Buildx
      run: |
        docker buildx build --build-arg PACKAGE_TYPE=${{ matrix.package_type }} --platform linux/arm64,linux/amd64 --output type=tar,dest=out.tar.gz .
        tar -xvf out.tar.gz
        mkdir -p /builds
        if [ "${{ matrix.package_type }}" = "apk" ]; then
          tar -C linux_arm64/ -czvf /builds/musl-arm64.tar.gz .
          tar -C linux_amd64/ -czvf /builds/musl-amd64.tar.gz .
        fi
        if [ "${{ matrix.package_type }}" = "deb" ]; then
          tar -C linux_arm64/ -czvf /builds/glibc-arm64.tar.gz .
          tar -C linux_amd64/ -czvf /builds/glibc-amd64.tar.gz .
        fi
    - name: Add Release Artifacts to the Github Release
      if: steps['release']['outputs']['published'] == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.release.outputs.release-git-tag}}
        files: /builds/*
